Modify cluster_properties.json because of botocore exception
botocore.exceptions.ClientError: An error occurred (ValidationException)
when calling the RunJobFlow operation: Master instance group must
have exactly 3 instances for HA clusters.

Signed-off-by: Ciaran Evans <ciaran@reliably.com>