Add GitHub Actions Workflows (#110)
* Add GitHub Actions Workflows

* Build and Test
* Build and Discover
* Release

Removed references to TravisCI

Signed-off-by: Ciaran Evans <ciaran@reliably.com>

* Add runs on

Signed-off-by: Ciaran Evans <ciaran@reliably.com>

* Modify cluster_properties.json because of botocore exception

botocore.exceptions.ClientError: An error occurred (ValidationException)
when calling the RunJobFlow operation: Master instance group must
have exactly 3 instances for HA clusters.

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: Javier Fernando Camacho Duarte <JACAMACH@bancolombia.com.co>